import type {
  ClientDetails,
  ClientListItem,
  Dashboard,
  InsurerListItem,
  PolicyDetails,
  RenewalDetails,
  RenewalListItem,
  TeamUser,
  WorkTaskDetails,
  WorkTaskListItem,
} from '../types/api'

export const teamUser: TeamUser = {
  publicId: 'user-admin',
  fullName: 'Admin A',
  email: 'admin.a@brokeros.test',
  role: 'BrokerAdmin',
  isActive: true,
}

export const clientListItem: ClientListItem = {
  publicId: 'client-1',
  clientCode: 'CLI-001',
  companyName: 'Alpha Logistics',
  clientType: 'Corporate',
  industry: 'Logistics',
  email: 'ops@alpha.test',
  phone: '+91 90000 00001',
  city: 'Mumbai',
  state: 'Maharashtra',
  isActive: true,
  assignedUserPublicId: teamUser.publicId,
  assignedUserName: teamUser.fullName,
  policyCount: 1,
  renewalCount: 1,
}

export const insurer: InsurerListItem = {
  publicId: 'insurer-1',
  name: 'Test New India',
  code: 'TNIA',
  isActive: true,
}

export function emptyPage<T>(items: T[] = []) {
  return {
    items,
    page: 1,
    pageSize: 50,
    totalCount: items.length,
    totalPages: items.length === 0 ? 0 : 1,
  }
}

export const createdClient: ClientDetails = {
  publicId: 'client-new',
  clientCode: 'CLI-100',
  companyName: 'Harbor Exports',
  clientType: 'Corporate',
  industry: 'Export',
  email: 'ops@harbor.test',
  phone: '+91 90000 33333',
  alternatePhone: null,
  addressLine1: '12 Dock Road',
  addressLine2: null,
  city: 'Chennai',
  state: 'Tamil Nadu',
  postalCode: '600001',
  country: 'India',
  assignedUserPublicId: null,
  assignedUserName: null,
  notes: null,
  isActive: true,
  policyCount: 0,
  activePolicyCount: 0,
  upcomingRenewalCount: 0,
  totalPremium: 0,
  createdAtUtc: '2026-08-13T10:00:00Z',
  modifiedAtUtc: null,
}

export const createdPolicy: PolicyDetails = {
  publicId: 'policy-new',
  policyNumber: 'POL-NEW-1',
  policyType: 'Property',
  status: 'Active',
  startDate: '2026-08-13',
  expiryDate: '2027-08-13',
  daysRemaining: 365,
  premium: 500000,
  sumInsured: 5000000,
  commissionPercentage: 10,
  commissionAmount: 50000,
  clientPublicId: clientListItem.publicId,
  clientName: clientListItem.companyName,
  insurerPublicId: insurer.publicId,
  insurerName: insurer.name,
  assignedUserPublicId: teamUser.publicId,
  assignedUserName: teamUser.fullName,
  renewalPublicId: 'renewal-new',
  renewalStatus: 'Upcoming',
  renewalPriority: 'Medium',
  renewalStage: 'NotStarted',
  notes: null,
  vehicleNumber: null,
  previousPolicyPublicId: null,
  nextPolicyPublicId: null,
  activities: [],
}

export const openRenewal: RenewalDetails = {
  publicId: 'renewal-1',
  policyPublicId: 'policy-1',
  policyNumber: 'POL-A-NEAR',
  policyType: 'Property',
  policyStatus: 'Active',
  premium: 100000,
  sumInsured: 1000000,
  startDate: '2025-09-12',
  expiryDate: '2026-09-12',
  renewalDate: '2026-09-12',
  daysRemaining: 30,
  status: 'Upcoming',
  priority: 'Medium',
  currentStage: 'NotStarted',
  clientPublicId: clientListItem.publicId,
  clientName: clientListItem.companyName,
  insurerPublicId: insurer.publicId,
  insurerName: insurer.name,
  assignedUserPublicId: teamUser.publicId,
  assignedUserName: teamUser.fullName,
  lastFollowUpAtUtc: null,
  nextFollowUpAtUtc: null,
  notes: null,
  createdAtUtc: '2026-01-01T00:00:00Z',
  nextPolicyPublicId: null,
  nextPolicyNumber: null,
  nextPolicyExpiryDate: null,
  nextRenewalPublicId: null,
  activities: [],
}

export const renewalListItem: RenewalListItem = {
  publicId: openRenewal.publicId,
  policyPublicId: openRenewal.policyPublicId,
  policyNumber: openRenewal.policyNumber,
  policyType: openRenewal.policyType,
  premium: openRenewal.premium,
  expiryDate: openRenewal.expiryDate,
  renewalDate: openRenewal.renewalDate,
  daysRemaining: openRenewal.daysRemaining,
  status: openRenewal.status,
  priority: openRenewal.priority,
  currentStage: openRenewal.currentStage,
  clientName: openRenewal.clientName,
  clientPublicId: openRenewal.clientPublicId,
  insurerName: openRenewal.insurerName,
  assignedUserPublicId: openRenewal.assignedUserPublicId,
  assignedUserName: openRenewal.assignedUserName,
  nextPolicyPublicId: null,
  nextPolicyNumber: null,
  nextPolicyExpiryDate: null,
}

export const openTask: WorkTaskDetails = {
  publicId: 'task-1',
  title: 'Call Alpha Logistics',
  description: 'Confirm renewal intent.',
  dueDateUtc: '2026-08-14T10:00:00Z',
  completedAtUtc: null,
  priority: 'High',
  status: 'Pending',
  clientPublicId: clientListItem.publicId,
  clientName: clientListItem.companyName,
  policyPublicId: 'policy-1',
  policyNumber: 'POL-A-NEAR',
  renewalPublicId: openRenewal.publicId,
  renewalPolicyNumber: 'POL-A-NEAR',
  assignedUserPublicId: teamUser.publicId,
  assignedUserName: teamUser.fullName,
  createdAtUtc: '2026-08-13T08:00:00Z',
  modifiedAtUtc: null,
  createdBy: 'tests',
}

export const taskListItem: WorkTaskListItem = {
  publicId: openTask.publicId,
  title: openTask.title,
  description: openTask.description,
  dueDateUtc: openTask.dueDateUtc,
  completedAtUtc: null,
  priority: openTask.priority,
  status: openTask.status,
  clientPublicId: openTask.clientPublicId,
  clientName: openTask.clientName,
  policyPublicId: openTask.policyPublicId,
  policyNumber: openTask.policyNumber,
  renewalPublicId: openTask.renewalPublicId,
  assignedUserPublicId: openTask.assignedUserPublicId,
  assignedUserName: openTask.assignedUserName,
}

export const dashboard: Dashboard = {
  currentUserName: 'Admin A',
  totalClients: 12,
  activePolicies: 20,
  renewalsOverdue: 3,
  renewalsDueToday: 1,
  renewalsDueWithin7Days: 4,
  renewalsDueWithin30Days: 8,
  renewalsDueWithin60Days: 11,
  premiumAtRisk: 850000,
  pendingTasks: 6,
  completedTasksToday: 2,
  pendingFollowUps: 1,
  upcomingRenewals: [
    {
      renewalPublicId: openRenewal.publicId,
      clientName: clientListItem.companyName,
      policyNumber: 'POL-A-NEAR',
      policyType: 'Property',
      insurerName: insurer.name,
      premium: 100000,
      expiryDate: '2026-09-12',
      daysRemaining: 30,
      status: 'Upcoming',
      priority: 'High',
      assignedUserName: teamUser.fullName,
    },
  ],
  todaysTasks: [
    {
      publicId: openTask.publicId,
      title: openTask.title,
      description: openTask.description,
      dueDateUtc: openTask.dueDateUtc,
      priority: 'High',
      status: 'Pending',
      clientName: clientListItem.companyName,
      policyNumber: 'POL-A-NEAR',
      renewalPublicId: openRenewal.publicId,
      assignedUserName: teamUser.fullName,
    },
  ],
}
